const scoreText=document.getElementById("score"),finalScoreText=document.getElementById("finalScore"),itemOneScoreText=document.getElementById("itemOneScore"),ingameScoreInput=document.getElementById("ingameScore"),artifactCountInput=document.getElementById("artifactCount"),itemThreeMultiplierText=document.getElementById("itemThreeMultiplier"),itemFourMultiplierText=document.getElementById("itemFourMultiplier"),itemThreeChecks=document.querySelectorAll(".item-three-check"),itemFourRadios=document.querySelectorAll(".item-four-radio"),keobeBossCountInput=document.getElementById("keobeBossCount"),itemFiveScoreText=document.getElementById("itemFiveScore"),itemSixScoreText=document.getElementById("itemSixScore"),itemSevenScoreText=document.getElementById("itemSevenScore"),dollarCells=document.querySelectorAll(".dollar-cell"),unreleasedUsageCountInput=document.getElementById("unreleasedUsageCount"),extraOriginiumCountInput=document.getElementById("extraOriginiumCount");
const selected={top:{activeRow:null,columns:{a:false,b:false,c:false,d:false,f:false,g:false}},bottom:{activeRow:null,columns:{a:false,b:false,c:false,d:false,f:false,g:false}},five:{activeRow:null,columns:{a:false,b:false,c:false,d:false,f:false,g:false}}};
const rowRules={top:{1:{base:-50,a:10,comboType:"bcd",comboScore:40,fg:100},2:{base:0,a:10,comboType:"bc",comboScore:50,fg:100},3:{base:60,a:80,comboType:"bcd",comboScore:120,fg:100},4:{base:80,a:120,comboType:"bc",comboScore:100,fg:100}},bottom:{5:{base:80,a:160,c:100,fg:100},6:{base:100,a:160,b:60,fg:100}}};
const fiveRules={7:{any:{base:0,a:20}},8:{A:{base:60,c:20},B:{base:20,b:30}},9:{A:{base:200,a:60,c:40},B:{base:100,a:40,b:40}},10:{onlyBottom3:true,A:{base:200,a:80,c:80}},11:{onlyBottom4:true,B:{base:20,b:20}},12:{A:{base:350,a:620,c:80},B:{base:240,a:320,b:80}},13:{A:{base:400,a:600,c:100},B:{base:325,a:475,b:90}}};
document.querySelectorAll(".select-button").forEach(btn=>btn.addEventListener("click",()=>{const g=btn.dataset.group,k=btn.dataset.key;selected[g].columns[k]=!selected[g].columns[k];updateScore()}));
document.querySelectorAll(".row-button").forEach(btn=>btn.addEventListener("click",()=>{const g=btn.dataset.group,r=btn.dataset.row;if(g==="five"&&!isFiveRowEnabled(r))return;selected[g].activeRow=selected[g].activeRow===r?null:r;updateScore()}));
[ingameScoreInput,artifactCountInput,keobeBossCountInput,unreleasedUsageCountInput,extraOriginiumCountInput].forEach(i=>i.addEventListener("input",updateScore));itemThreeChecks.forEach(c=>c.addEventListener("change",updateScore));itemFourRadios.forEach(r=>r.addEventListener("change",updateScore));dollarCells.forEach(c=>c.addEventListener("click",()=>{c.classList.toggle("active");updateScore()}));
function updateScore(){clearAll();validateFiveSelection();updateFiveDisplay();let itemTwoScore=calcGroup("top")+calcGroup("bottom")+calcFiveGroup();const ingame=Number(ingameScoreInput.value)||0,artifact=Number(artifactCountInput.value)||0,itemOne=artifact>100?Math.floor((100-artifact)*7.5):0,itemFive=calcItemFiveScore(),itemSix=calcItemSixScore(),itemSeven=calcItemSevenScore(),base=ingame+itemOne+itemTwoScore+itemSix,itemThree=calcItemThreeMultiplier(),itemFour=calcItemFourMultiplier(),totalMultiplier=1+(itemThree-1)+(itemFour-1),final=base*totalMultiplier+itemFive+itemSeven;scoreText.textContent=itemTwoScore+"점";itemOneScoreText.textContent=itemOne+"점";itemThreeMultiplierText.textContent=fmtMul(itemThree)+"배";itemFourMultiplierText.textContent=fmtMul(itemFour)+"배";itemFiveScoreText.textContent=itemFive+"점";itemSixScoreText.textContent=itemSix+"점";itemSevenScoreText.textContent=itemSeven+"점";finalScoreText.textContent=fmtScore(final)+"점"}
function calcItemFiveScore(){let t=0;dollarCells.forEach(c=>{if(c.classList.contains("active"))t+=Number(c.dataset.dollar)||0});return t*(-5)}function calcItemSixScore(){const c=Number(unreleasedUsageCountInput.value)||0;if(c<=0)return 0;if(c===1)return -100;return -100-500*(c-1)}function calcItemSevenScore(){const c=Number(extraOriginiumCountInput.value)||0;return c*(-50)}
function calcItemThreeMultiplier(){let s=0;itemThreeChecks.forEach(c=>{if(c.checked)s+=Number(c.dataset.multiplier)-1});s+=(Number(keobeBossCountInput.value)||0)*0.005;return 1+s}function calcItemFourMultiplier(){const r=document.querySelector('.item-four-radio:checked');return r?Number(r.value):1}
function calcGroup(g){const row=selected[g].activeRow,cols=getActiveColumns(g);updateColumnUI(g,cols);updateRowUI(g);if(!row)return 0;const rule=rowRules[g][row];let sum=rule.base;activateCell(g,row,"base");if(cols.a&&rule.a!==undefined){sum+=rule.a;activateCell(g,row,"a")}if(g==="top"){if(rule.comboType==="bcd"&&cols.b&&cols.c&&cols.d){sum+=rule.comboScore;activateCell(g,row,"bcd")}if(rule.comboType==="bc"&&cols.b&&cols.c){sum+=rule.comboScore;activateCell(g,row,"bc")}}if(g==="bottom"){if(cols.c&&rule.c!==undefined){sum+=rule.c;activateCell(g,row,"c")}if(cols.b&&rule.b!==undefined){sum+=rule.b;activateCell(g,row,"b")}}if(cols.f&&cols.g){sum+=rule.fg;activateCell(g,row,"fg")}setRowTotal(g,row,sum);return sum}
function calcFiveGroup(){const row=selected.five.activeRow,cols=getActiveColumns("five");updateColumnUI("five",cols);updateRowUI("five");updateFiveDisabledUI();if(!row||!isFiveRowEnabled(row))return 0;const rule=fiveRules[row],active=rule.any||rule[getFiveCase()];if(!active)return 0;let sum=active.base;activateCell("five",row,"base");["a","b","c","d","f","g"].forEach(k=>{if(cols[k]&&active[k]!==undefined){sum+=active[k];activateCell("five",row,k)}});setRowTotal("five",row,sum);return sum}
function getActiveColumns(g){const cols={...selected[g].columns};if(g==="top"){const r=selected.top.activeRow;if(r==="2"||r==="4")cols.c=true}if(g==="bottom"){const r=selected.bottom.activeRow;if(r==="5"){cols.b=true;cols.d=true}if(r==="6")cols.c=true}if(g==="five"){const r=selected.bottom.activeRow;if(r==="5"){cols.b=true;cols.d=true}if(r==="6")cols.c=true}return cols}function getFiveCase(){return selected.bottom.activeRow==="6"?"B":"A"}function isFiveRowEnabled(row){const rule=fiveRules[row];if(!rule)return false;if(rule.onlyBottom3)return selected.bottom.activeRow==="5";if(rule.onlyBottom4)return selected.bottom.activeRow==="6";return true}function validateFiveSelection(){if(selected.five.activeRow&&!isFiveRowEnabled(selected.five.activeRow))selected.five.activeRow=null}
function updateFiveDisplay(){const attr=getFiveCase()==="B"?"b":"a";document.querySelectorAll('[data-group="five"].score-cell').forEach(cell=>{let v="";if(cell.dataset.any!==undefined)v=cell.dataset.any;else if(cell.dataset[attr]!==undefined)v=cell.dataset[attr];cell.textContent=v===""?"":signed(v)})}function signed(v){const n=Number(v);return Number.isNaN(n)?v:(n>=0?"+"+n:String(n))}function fmtMul(v){return Number(v.toFixed(3)).toString()}function fmtScore(v){return Number(v.toFixed(2)).toString()}
function updateColumnUI(g,cols){document.querySelectorAll(`.select-button[data-group="${g}"]`).forEach(btn=>btn.classList.toggle("active",!!cols[btn.dataset.key]))}function updateRowUI(g){document.querySelectorAll(`.row-button[data-group="${g}"]`).forEach(btn=>btn.classList.toggle("active",selected[g].activeRow===btn.dataset.row))}function updateFiveDisabledUI(){document.querySelectorAll('.row-button[data-group="five"]').forEach(btn=>{const en=isFiveRowEnabled(btn.dataset.row);btn.disabled=!en;btn.classList.toggle("disabled",!en);if(!en)btn.classList.remove("active")})}function activateCell(g,r,t){const cell=document.querySelector(`[data-group="${g}"][data-row="${r}"][data-score="${t}"]`);if(cell)cell.classList.add("active")}function setRowTotal(g,r,sum){const c=document.querySelector(`[data-group="${g}"][data-row-total="${r}"]`);if(c){c.textContent=sum+"점";c.classList.add("active")}}function clearAll(){document.querySelectorAll(".score-cell").forEach(e=>e.classList.remove("active"));document.querySelectorAll(".total-cell").forEach(e=>{e.classList.remove("active");e.textContent="0점"})}updateScore();
